// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: src/protos/chat/chat.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_src_protos_chat_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_chat_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_src_protos_chat_chat_proto_rawDescGZIP(), []int{0}
}

type MessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	IsPrivate     bool                   `protobuf:"varint,4,opt,name=isPrivate,proto3" json:"isPrivate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	mi := &file_src_protos_chat_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_chat_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_src_protos_chat_chat_proto_rawDescGZIP(), []int{1}
}

func (x *MessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MessageRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *MessageRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *MessageRequest) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

type MessageRespone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRespone) Reset() {
	*x = MessageRespone{}
	mi := &file_src_protos_chat_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRespone) ProtoMessage() {}

func (x *MessageRespone) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_chat_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRespone.ProtoReflect.Descriptor instead.
func (*MessageRespone) Descriptor() ([]byte, []int) {
	return file_src_protos_chat_chat_proto_rawDescGZIP(), []int{2}
}

func (x *MessageRespone) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_src_protos_chat_chat_proto protoreflect.FileDescriptor

const file_src_protos_chat_chat_proto_rawDesc = "" +
	"\n" +
	"\x1asrc/protos/chat/chat.proto\x12\x04chat\"\a\n" +
	"\x05Empty\"l\n" +
	"\x0eMessageRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x1c\n" +
	"\tisPrivate\x18\x04 \x01(\bR\tisPrivate\"*\n" +
	"\x0eMessageRespone\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2n\n" +
	"\x04Chat\x124\n" +
	"\x04Send\x12\x14.chat.MessageRequest\x1a\x14.chat.MessageRespone\"\x00\x120\n" +
	"\aConnect\x12\v.chat.Empty\x1a\x14.chat.MessageRequest\"\x000\x01B\aZ\x05chat/b\x06proto3"

var (
	file_src_protos_chat_chat_proto_rawDescOnce sync.Once
	file_src_protos_chat_chat_proto_rawDescData []byte
)

func file_src_protos_chat_chat_proto_rawDescGZIP() []byte {
	file_src_protos_chat_chat_proto_rawDescOnce.Do(func() {
		file_src_protos_chat_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_protos_chat_chat_proto_rawDesc), len(file_src_protos_chat_chat_proto_rawDesc)))
	})
	return file_src_protos_chat_chat_proto_rawDescData
}

var file_src_protos_chat_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_src_protos_chat_chat_proto_goTypes = []any{
	(*Empty)(nil),          // 0: chat.Empty
	(*MessageRequest)(nil), // 1: chat.MessageRequest
	(*MessageRespone)(nil), // 2: chat.MessageRespone
}
var file_src_protos_chat_chat_proto_depIdxs = []int32{
	1, // 0: chat.Chat.Send:input_type -> chat.MessageRequest
	0, // 1: chat.Chat.Connect:input_type -> chat.Empty
	2, // 2: chat.Chat.Send:output_type -> chat.MessageRespone
	1, // 3: chat.Chat.Connect:output_type -> chat.MessageRequest
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_protos_chat_chat_proto_init() }
func file_src_protos_chat_chat_proto_init() {
	if File_src_protos_chat_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_protos_chat_chat_proto_rawDesc), len(file_src_protos_chat_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_protos_chat_chat_proto_goTypes,
		DependencyIndexes: file_src_protos_chat_chat_proto_depIdxs,
		MessageInfos:      file_src_protos_chat_chat_proto_msgTypes,
	}.Build()
	File_src_protos_chat_chat_proto = out.File
	file_src_protos_chat_chat_proto_goTypes = nil
	file_src_protos_chat_chat_proto_depIdxs = nil
}
